default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: qualitrackr_development

test:
  <<: *default
  database: qualitrackr_test

production:
  <<: *default
  database: qualitrackr_production


production:
  <<: *default
  database: qualitrackr_production
  username: qualitrackr
  password: <%= ENV["QUALITRACKR_DATABASE_PASSWORD"] %>